#1 NO USER DELETION
#2 SOFT DELETE EXPENSE
#3 CONTRIBUTORS CANNOT BE UPDATED FOR AN EXPENSE BUT ONLY THE AMOUNT CAN BE EDITED TO ZERO
#4 GROUP HARD DELETE
#5 CANNOT LEAVE GROUP BEFORE SETTLEMENT
#6 GROUP STATE WILL BE COMMITED PERMANANTLY ONCE A MEMBER LEAVES A GROUP
#7 GROUP CANNOT BE DELETED BEFORE SETTLE
#8 MEMBER CAN ONLY BE ADDED BY INVITATION
#9 ONE USER CAN ONLY BE INVITED BY ONE MEMBER OF THE GROUP AT A TIME
#10 IF A MEMBER LEAVE A GROUP, DELETE ALL PENDING INVITATION MADE BY THAT MEMBER INSIDE SAME GROUP.

